name: code-scanner

services:

  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - common-network

  db-migrator:
    container_name: db-migrator
    build:
      context: ../
      dockerfile: app/db_migrator/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - common-network
    restart: on-failure:5


  identity-service:
    container_name: identity-service
    build:
      context: ../
      dockerfile: app/identity-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    restart: no
    networks:
      - common-network

  user-service:
    container_name: user-service
    build:
      context: ../
      dockerfile: app/user-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    restart: no
    networks:
      - common-network

  updates-service:
    container_name: updates-service
    build:
      context: ../
      dockerfile: app/updates-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    restart: no
    networks:
      - common-network


  nginx-proxy:
    build:
      context: ../app/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - common-network
    restart: unless-stopped
    depends_on:
      - identity-service
      - user-service
      - updates-service
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt:ro



volumes:
  postgres_data:

networks:
  common-network:
    external: false

