global:
  scrape_interval: 15s

scrape_configs:

  # Fast api application

  - job_name: "identity-service"
    static_configs:
      - targets: [ "identity-service:5000" ]

  - job_name: "update-service"
    static_configs:
      - targets: [ "update-service:5000" ]

  - job_name: "user-service"
    static_configs:
      - targets: [ "user-service:5000" ]
